sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev  -t sanketdocker1/docker-react .

script:
  - docker run -e CI=true sanketdocker1/docker-react npm run test
